dbt_project:
  outputs:
    dev:
      account: "{{ env_var('DBT_ACCOUNT') }}"
      database: FIVETRAN_DATABASE
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: FIVETRAN_ROLE
      schema: GOOGLE_DRIVE
      threads: 2
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: FIVETRAN_WAREHOUSE
  target: dev

