name: dbt production run on push branches to main

on:
  push:
    branches: [ master ]

env:
  DBT_ACCOUNT: ${{ secrets.DBT_ACCCOUNT }}
  DBT_USER: ${{ secrets.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

jobs:
  dbt_run:
    name: dbt refresh and test on push branches to main
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Install dbt packages
        run: dbt deps
        working-directory: ./

      - name: Run dbt
        run: dbt run --profiles-dir . --target dev
        env:
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

